"""Build a deterministic, read-only Python module/import map with the standard library."""

from __future__ import annotations

import argparse
import ast
import os
import sys
import tempfile
import tokenize
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

MARKER = GENERATOR_MARKER = "<!-- Generated by tools/context_graph.py; do not edit. -->"
MAX_FILES = DEFAULT_MAX_FILES = 400
MAX_CHARS = DEFAULT_MAX_OUTPUT_CHARS = 30_000
EXCLUDED_DIRS = {
    ".git", ".hg", ".svn", ".venv", "venv", "env", ".tox", ".nox",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".hypothesis",
    "__pycache__", "__pypackages__", "node_modules", "build", "dist", "target",
}


class GraphError(Exception):
    """An actionable source or output error."""


@dataclass(frozen=True)
class Module:
    path: str
    name: str | None
    symbols: tuple[str, ...]
    imports: tuple[str | None, ...]


def _inside(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def _module_name(path: Path, root: Path) -> str | None:
    parts = list(path.relative_to(root).parts)
    if parts and parts[-1] == "__init__.py":
        parts.pop()
    elif parts:
        parts[-1] = Path(parts[-1]).stem
    if not parts or any(not part.isidentifier() for part in parts):
        return None
    return ".".join(parts)


def _roots(project: Path, requested: Sequence[Path] | None) -> tuple[Path, ...]:
    roots: set[Path] = set()
    for source in requested or (Path("."),):
        candidate = source if source.is_absolute() else project / source
        try:
            root = candidate.resolve(strict=True)
        except OSError as error:
            raise GraphError(f"cannot resolve source root '{source}': {error}") from error
        if not root.is_dir() or not _inside(root, project):
            raise GraphError(f"source root must be a directory inside --root: {source}")
        roots.add(root)
    return tuple(sorted(roots, key=lambda item: (len(item.parts), item.as_posix())))


def _python_files(roots: Sequence[Path], limit: int) -> tuple[Path, ...]:
    found: set[Path] = set()

    def scan_error(error: OSError) -> None:
        raise GraphError(f"cannot scan '{error.filename}': {error.strerror or error}") from error

    for root in roots:
        for current, directories, names in os.walk(root, followlinks=False, onerror=scan_error):
            folder = Path(current)
            directories[:] = sorted(
                name
                for name in directories
                if name not in EXCLUDED_DIRS and not (folder / name).is_symlink()
            )
            found.update(
                folder / name
                for name in names
                if name.endswith(".py") and not (folder / name).is_symlink()
            )
            if len(found) > limit:
                raise GraphError(
                    f"Python file limit exceeded ({limit}); narrow --source or raise --max-files"
                )
    if not found:
        raise GraphError("no Python files found in the selected roots")
    return tuple(sorted(found, key=lambda item: item.as_posix()))


def _owner(path: Path, roots: Sequence[Path]) -> Path:
    return max((root for root in roots if _inside(path, root)), key=lambda root: len(root.parts))


def _imports(
    tree: ast.Module,
    name: str | None,
    is_package: bool,
    module_names: set[str],
) -> tuple[str | None, ...]:
    imports: set[str | None] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            parts = name.split(".") if name else []
            if not is_package and parts:
                parts.pop()
            ascents = node.level - 1
            valid = ascents < len(parts)
            if valid and ascents:
                parts = parts[:-ascents]
            if node.module:
                parts.extend(node.module.split("."))
            base = ".".join(parts) if valid else ""
            if node.level == 0:
                base = node.module or ""
            if not valid or not base:
                imports.add(None)
                continue
            child = next(
                (f"{base}.{alias.name}" for alias in node.names
                 if alias.name != "*" and f"{base}.{alias.name}" in module_names),
                None,
            )
            imports.add(child or base)
    return tuple(sorted(imports, key=lambda value: value or ""))


def _symbols(tree: ast.Module) -> tuple[str, ...]:
    symbols: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            methods = [
                item.name
                for item in node.body
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
            ]
            suffix = f" ({', '.join(methods)})" if methods else ""
            line_end = getattr(node, "end_lineno", node.lineno)
            symbols.append(f"class {node.name} L{node.lineno}-L{line_end}{suffix}")
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            kind = "async function" if isinstance(node, ast.AsyncFunctionDef) else "function"
            line_end = getattr(node, "end_lineno", node.lineno)
            symbols.append(f"{kind} {node.name} L{node.lineno}-L{line_end}")
    return tuple(symbols)


def build_graph(
    project_root: Path,
    source_roots: Sequence[Path] | None = None,
    max_files: int = MAX_FILES,
) -> tuple[Module, ...]:
    if max_files < 1:
        raise GraphError("--max-files must be positive")
    try:
        project = project_root.expanduser().resolve(strict=True)
    except OSError as error:
        raise GraphError(f"cannot resolve project root '{project_root}': {error}") from error
    if not project.is_dir():
        raise GraphError(f"project root is not a directory: {project}")

    roots = _roots(project, source_roots)
    paths = _python_files(roots, max_files)
    names = {path: _module_name(path, _owner(path, roots)) for path in paths}
    module_names = [name for name in names.values() if name]
    seen_names: set[str] = set()
    for module_name in module_names:
        if module_name in seen_names:
            raise GraphError(
                f"ambiguous module '{module_name}' in selected roots; narrow --source"
            )
        seen_names.add(module_name)

    modules: list[Module] = []
    for path in paths:
        try:
            with tokenize.open(path) as stream:
                tree = ast.parse(stream.read(), filename=str(path))
        except (OSError, UnicodeError, SyntaxError, ValueError) as error:
            detail = f"{error.msg} at line {error.lineno}" if isinstance(error, SyntaxError) else str(error)
            raise GraphError(f"cannot parse '{path}': {detail}") from error
        modules.append(Module(
            path=path.relative_to(project).as_posix(),
            name=names[path],
            symbols=_symbols(tree),
            imports=_imports(tree, names[path], path.name == "__init__.py", set(module_names)),
        ))
    return tuple(modules)


def render_graph(project_root: Path, source_roots: Sequence[Path] | None,
                 modules: Sequence[Module], max_chars: int = MAX_CHARS) -> str:
    if max_chars < 1:
        raise GraphError("--max-output-chars must be positive")
    project = project_root.expanduser().resolve()
    roots = _roots(project, source_roots)
    names = {module.name: module.path for module in modules if module.name}
    labels = ["." if root == project else root.relative_to(project).as_posix() for root in roots]
    lines = [
        MARKER, "# Python Context Map", f"Source roots: {', '.join(f'`{label}`' for label in labels)}",
        f"Modules: {len(modules)}", "Imports are syntax-only; external imports remain unresolved.",
        "Verify source before relying on this map.", "", "## Modules",
    ]
    for module in modules:
        name = f" `{module.name}`" if module.name else " (not import-resolvable)"
        lines.append(f"- `{module.path}`{name}: {'; '.join(module.symbols) or '(no top-level definitions)'}")
    lines.extend(["", "## Imports"])
    for module in modules:
        for imported in module.imports:
            resolved = names.get(imported) if imported else None
            edge = f" [in-scope: `{resolved}` ({names[imported]})]" if resolved else " [external/outside scope]"
            lines.append(f"- `{module.path}` -> `{imported or 'unresolved relative import'}`{edge}")
    output = "\n".join(lines) + "\n"
    if len(output) > max_chars:
        raise GraphError(f"map exceeds --max-output-chars={max_chars}; narrow roots or raise the limit")
    return output


def write_graph(project: Path, content: str, force: bool = False) -> tuple[Path, bool]:
    destination = project / ".hase" / "context.md"
    if destination.exists():
        try:
            existing = destination.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as error:
            raise GraphError(f"cannot read '{destination}': {error}") from error
        if existing.splitlines()[:1] != [MARKER] and not force:
            raise GraphError(f"refusing to replace handwritten '{destination}'; review and use --force")
        if existing == content:
            return destination, False

    temporary: Path | None = None
    try:
        destination.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=destination.parent,
                                         prefix=".context-", suffix=".tmp", delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(content)
        os.replace(temporary, destination)
    except OSError as error:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise GraphError(f"cannot write '{destination}': {error}") from error
    return destination, True


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a local Python context map using the standard library.")
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--source", type=Path, action="append", default=None)
    parser.add_argument("--max-files", type=int, default=MAX_FILES)
    parser.add_argument("--max-output-chars", type=int, default=MAX_CHARS)
    parser.add_argument("--force", action="store_true", help="replace non-generated context after review")
    args = parser.parse_args(argv)
    try:
        root = args.root.expanduser().resolve(strict=True)
        modules = build_graph(root, args.source, args.max_files)
        content = render_graph(root, args.source, modules, args.max_output_chars)
        output, changed = write_graph(root, content, args.force)
    except (GraphError, OSError) as error:
        print(f"context_graph: error: {error}", file=sys.stderr)
        return 2
    print(f"context_graph: {'updated' if changed else 'up-to-date'} {output} ({len(modules)} modules, {len(content)} characters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
